/* soapcalcService.cpp
   Generated by gSOAP 2.8.23 from calc.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapcalcService.h"

calcService::calcService()
{	this->soap = soap_new();
	this->soap_own = true;
	calcService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

calcService::calcService(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	calcService_init(_soap->imode, _soap->omode);
}

calcService::calcService(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	calcService_init(iomode, iomode);
}

calcService::calcService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	calcService_init(imode, omode);
}

calcService::~calcService()
{	if (this->soap_own)
		soap_free(this->soap);
}

void calcService::calcService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "urn:calc", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void calcService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void calcService::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	calcService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
calcService *calcService::copy()
{	calcService *dup = SOAP_NEW_COPY(calcService);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

int calcService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int calcService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int calcService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int calcService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int calcService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int calcService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void calcService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void calcService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *calcService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void calcService::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *calcService::soap_header()
{	return this->soap->header;
}

int calcService::run(int port)
{	if (soap_valid_socket(this->soap->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				break;
			soap_destroy(this->soap);
			soap_end(this->soap);
		}
	}
	return this->soap->error;
}

SOAP_SOCKET calcService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET calcService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int calcService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif

int calcService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->soap->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->soap->max_keep_alive > 0 && !--k)
			this->soap->keep_alive = 0;
#endif

		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if (dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns2__add(struct soap*, calcService*);
static int serve_ns2__sub(struct soap*, calcService*);
static int serve_ns2__mul(struct soap*, calcService*);
static int serve_ns2__div(struct soap*, calcService*);
static int serve_ns2__pow(struct soap*, calcService*);

int calcService::dispatch()
{	return dispatch(this->soap);
}

int calcService::dispatch(struct soap* soap)
{	calcService_init(soap->imode, soap->omode);
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:add"))
		return serve_ns2__add(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ns2:sub"))
		return serve_ns2__sub(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ns2:mul"))
		return serve_ns2__mul(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ns2:div"))
		return serve_ns2__div(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ns2:pow"))
		return serve_ns2__pow(soap, this);
	return soap->error = SOAP_NO_METHOD;
}

static int serve_ns2__add(struct soap *soap, calcService *service)
{	struct ns2__add soap_tmp_ns2__add;
	struct ns2__addResponse soap_tmp_ns2__addResponse;
	soap_default_ns2__addResponse(soap, &soap_tmp_ns2__addResponse);
	soap_default_ns2__add(soap, &soap_tmp_ns2__add);
	if (!soap_get_ns2__add(soap, &soap_tmp_ns2__add, "ns2:add", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->add(soap_tmp_ns2__add.a, soap_tmp_ns2__add.b, soap_tmp_ns2__addResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns2__addResponse(soap, &soap_tmp_ns2__addResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__addResponse(soap, &soap_tmp_ns2__addResponse, "ns2:addResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__addResponse(soap, &soap_tmp_ns2__addResponse, "ns2:addResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns2__sub(struct soap *soap, calcService *service)
{	struct ns2__sub soap_tmp_ns2__sub;
	struct ns2__subResponse soap_tmp_ns2__subResponse;
	soap_default_ns2__subResponse(soap, &soap_tmp_ns2__subResponse);
	soap_default_ns2__sub(soap, &soap_tmp_ns2__sub);
	if (!soap_get_ns2__sub(soap, &soap_tmp_ns2__sub, "ns2:sub", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->sub(soap_tmp_ns2__sub.a, soap_tmp_ns2__sub.b, soap_tmp_ns2__subResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns2__subResponse(soap, &soap_tmp_ns2__subResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__subResponse(soap, &soap_tmp_ns2__subResponse, "ns2:subResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__subResponse(soap, &soap_tmp_ns2__subResponse, "ns2:subResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns2__mul(struct soap *soap, calcService *service)
{	struct ns2__mul soap_tmp_ns2__mul;
	struct ns2__mulResponse soap_tmp_ns2__mulResponse;
	soap_default_ns2__mulResponse(soap, &soap_tmp_ns2__mulResponse);
	soap_default_ns2__mul(soap, &soap_tmp_ns2__mul);
	if (!soap_get_ns2__mul(soap, &soap_tmp_ns2__mul, "ns2:mul", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->mul(soap_tmp_ns2__mul.a, soap_tmp_ns2__mul.b, soap_tmp_ns2__mulResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns2__mulResponse(soap, &soap_tmp_ns2__mulResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__mulResponse(soap, &soap_tmp_ns2__mulResponse, "ns2:mulResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__mulResponse(soap, &soap_tmp_ns2__mulResponse, "ns2:mulResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns2__div(struct soap *soap, calcService *service)
{	struct ns2__div soap_tmp_ns2__div;
	struct ns2__divResponse soap_tmp_ns2__divResponse;
	soap_default_ns2__divResponse(soap, &soap_tmp_ns2__divResponse);
	soap_default_ns2__div(soap, &soap_tmp_ns2__div);
	if (!soap_get_ns2__div(soap, &soap_tmp_ns2__div, "ns2:div", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->div(soap_tmp_ns2__div.a, soap_tmp_ns2__div.b, soap_tmp_ns2__divResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns2__divResponse(soap, &soap_tmp_ns2__divResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__divResponse(soap, &soap_tmp_ns2__divResponse, "ns2:divResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__divResponse(soap, &soap_tmp_ns2__divResponse, "ns2:divResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns2__pow(struct soap *soap, calcService *service)
{	struct ns2__pow soap_tmp_ns2__pow;
	struct ns2__powResponse soap_tmp_ns2__powResponse;
	soap_default_ns2__powResponse(soap, &soap_tmp_ns2__powResponse);
	soap_default_ns2__pow(soap, &soap_tmp_ns2__pow);
	if (!soap_get_ns2__pow(soap, &soap_tmp_ns2__pow, "ns2:pow", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->pow(soap_tmp_ns2__pow.a, soap_tmp_ns2__pow.b, soap_tmp_ns2__powResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns2__powResponse(soap, &soap_tmp_ns2__powResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__powResponse(soap, &soap_tmp_ns2__powResponse, "ns2:powResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__powResponse(soap, &soap_tmp_ns2__powResponse, "ns2:powResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
